@echo off
REM ============================================================
REM STM32 Debug Tools - Configuration
REM Auto-generated by install.bat
REM ============================================================

REM Keil MDK Path
if not defined KEIL_PATH set "KEIL_PATH=C:\Keil_v5\UV4\UV4.exe"

REM STM32CubeProgrammer Path
if not defined STLINK_PATH set "STLINK_PATH=C:\STMicroelectronics\STM32Cube\STM32CubeProgrammer\bin\STM32_Programmer_CLI.exe"

REM Default Serial Port
if not defined DEFAULT_SERIAL_PORT set "DEFAULT_SERIAL_PORT=COM11"
if not defined DEFAULT_SERIAL_BAUD set "DEFAULT_SERIAL_BAUD=115200"

REM Tools Directory (auto-detect)
set "TOOLS_DIR=%~dp0"

REM Log Directory
if not defined LOG_DIR set "LOG_DIR=%TOOLS_DIR%logs"
if not exist "%LOG_DIR%" mkdir "%LOG_DIR%"
